### ISSUE TITLE
Strange way to start zabbix-agent under CentOS

### ISSUE THREAD

**Issue by varnav** [indigo-dc/ansible-role-zabbix-agent#1]
Hello!

I've noticed a strange way you're starting zabbix agent in CentOS:

```
  - name: Start Zabbix agent in Centos 7
    shell: pgrep zabbix_agentd || /usr/sbin/zabbix_agentd
    when: zabbix_service|failed
```

Why this step is used? 
`service: name=zabbix-agent state=started`
that you already have works fine in CentOS 7

BTW, changing it to

`service: name=zabbix-agent state=started enabled=yes`

would be better, as it will autostart on boot then.

**Comment by micafer** [comment]
Hi @varnav 
This recipe has been created to be launched in VMs and in Docker containers.
In non privileged Docker containers the ansible "service" module does not work.
So we add this step to launch the service in Docker containers when the "zabbix_service" fails.
But you are right that we can add the "enabled=yes" to start the service on boot.
I have added it.
